4 7 transscript
Virtual-Coffee/podcast-transcripts pull request #110
Opened 2023-10-22 18:58 UTC by ClJarvis

Improve transcription Season 4 Episode 7
## Description

This PR improves transcript Season 4 Episode 7 with Jessica Wilkins.  Growing your tech career through writing.

## Related Issue

Closes #52

2023-10-23 19:24 UTC, adiati98 commented
Hey @ClJarvis,
Thanks for your PR!

You added there are two episodes files here.
Can you please remove the Season 3 Episode 9 as it's not related to this PR?

Thank you! :)

2023-10-23 19:34 UTC, ClJarvis commented
@adiati98 deleted file.

2023-10-23 19:37 UTC, adiati98 commented
@ClJarvis I see a conflicting files here. Please resolve it first :)
I think you should `git pull` the branch from your remote to your local, then push it back.

2023-10-23 19:50 UTC, adiati98 commented
@ClJarvis it might be easier for you to copy paste the commands.

Click the "Use the command line" link in the conflicts box here. It will open the commands as my previous screenshot.

![use the command line](https://github.com/Virtual-Coffee/podcast-transcripts/assets/45172775/efb8ea10-979d-44c0-91f7-aa64635af680)

2023-10-23 21:11 UTC, adiati98 requested changes
Hi @ClJarvis,
Can you please re-check everything?
I found conversations without timestamps and no or not correct speakers. I haven't checked until the end. But please re-check everything and fix anything necessary.

Thank you :)

2023-10-23 21:11 UTC, adiati98 commented on episodes/4_7.srt
> +Bekah: same
Why there is no timestamp here?

2023-10-23 21:11 UTC, adiati98 commented on episodes/4_7.srt
>  totally thought this was just
There is also no timestamp here and the speaker here is Jessica.

2023-10-23 21:50 UTC, ClJarvis commented
> @ClJarvis it might be easier for you to copy paste the commands.
> 
> Click the "Use the command line" link in the conflicts box here. It will open the commands as my previous screenshot.
> 
> ![use the command line](https://user-images.githubusercontent.com/45172775/277460858-efb8ea10-979d-44c0-91f7-aa64635af680.png)

Where is the conflicts box?

2023-10-23 21:55 UTC, adiati98 commented
> > @ClJarvis it might be easier for you to copy paste the commands.
> > 
> > Click the "Use the command line" link in the conflicts box here. It will open the commands as my previous screenshot.
> > 
> > ![use the command line](https://user-images.githubusercontent.com/45172775/277460858-efb8ea10-979d-44c0-91f7-aa64635af680.png)
> 
> Where is the conflicts box?

You should see it when you scroll down. If you don't, you can refer to my other screenshot.

2023-10-23 22:01 UTC, ClJarvis commented
> > > @ClJarvis it might be easier for you to copy paste the commands.
> > > Click the "Use the command line" link in the conflicts box here. It will open the commands as my previous screenshot.
> > > ![use the command line](https://user-images.githubusercontent.com/45172775/277460858-efb8ea10-979d-44c0-91f7-aa64635af680.png)
> > 
> > 
> > Where is the conflicts box?
> 
> You should see it when you scroll down. If you don't, you can refer to my other screenshot.

Oh it's grayed out and disabled for me.

2023-10-24 04:33 UTC, adiati98 commented
> > > > @ClJarvis it might be easier for you to copy paste the commands.
> > > > Click the "Use the command line" link in the conflicts box here. It will open the commands as my previous screenshot.
> > > > ![use the command line](https://user-images.githubusercontent.com/45172775/277460858-efb8ea10-979d-44c0-91f7-aa64635af680.png)
> > > 
> > > 
> > > Where is the conflicts box?
> > 
> > You should see it when you scroll down. If you don't, you can refer to my other screenshot.
> 
> Oh it's grayed out and disabled for me. 
> 
> 

As I mentioned in the previous post, click the link that I highlighted.

2023-10-24 14:01 UTC, ClJarvis commented
Maybe I was unclear. That is grayed out and disabled for me. I do not have write access to it. 

I removed the extra file. Made changes to 4_7 and submitted another PR. 

![conflicts](https://github.com/Virtual-Coffee/podcast-transcripts/assets/10702993/64c2dd9e-44c2-424f-8627-bc5b06488b03)

2023-10-24 14:16 UTC, adiati98 commented
Thanks for the clarification, @ClJarvis!
I will close this PR as it's moved to #111. :)

2023-10-24 14:16 UTC, closed without merging