update transcript for 4_2
Virtual-Coffee/podcast-transcripts pull request #78
Opened 2022-10-10 00:01 UTC by ClJarvis

### Description
Improved auto generated transcripts for  Season 4 Episode 2 with Todd Libby.
Ran yarn check-srt to fix incorrect timestamp formatting.
Fixed colon error

closes #47

2022-10-10 12:52 UTC, danieltott commented
@adiati98 can you take a look at this when you get a chance?

2022-10-10 12:59 UTC, adiati98 commented
@danieltott sure!

2022-10-10 14:54 UTC, adiati98 requested changes
Hi @ClJarvis,
I've dropped some reviews 😊

Also, we are keeping filler words *except* `um` and `uh`.
So please remove these filler words.

I might missed things, so please re-check and make sure:
- No colon in the middle of the line to prevent problematic behavior on the website.
    When a there's a change of speaker, put them in new line with new timestamp (I gave an example in one of the review).
- Capitalize names, new sentence, etc.
- Use `single dash` instead of `comma` for repeated word(s) and give space aftert the dash.

You can refer to our [guildeline](https://github.com/Virtual-Coffee/podcast-transcripts/blob/main/Transcriptions-Guidelines.md#virtual-coffee-podcast-transcriptions-guidelines) for transcribing.

If you have any question, please let me know.
Thank you, Chris!

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
> +Bekah: I just think it's-it's
We want to give a space after the dash for repeated word.

e.g.:

```markdown
Bekah: I just think it's- it's
```

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
>  way back in the day. I, I used
I thinks this one is a repeat word?

`way back in the day. I- I used`

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
>  WAVE extension, um, the axe, I
Is `the axe` a name? If so, we need to capitalize here.

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
>  Mac app and everything, um, and
I believe this is `NVDA` and not `and VDA`

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
> +the tools I use. ha ha.
Capitalize the `Ha ha` after a period.

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
> +You know what I mean? Todd: umm
We cannot have colon here.

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
> +it needs an empty alt text. And
Let's keep this uniform with `ALT text` :)

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
> +Todd: Yes Dan: Right.
We cannot have colon here for the change of speaker.

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
> +Bekah: So ki, this has kind of
Is this an unfinished word? If so, it should be `So ki- this ...`

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
> +Dan: oh. Yeah.
Please capitalize the `Oh`.

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
> +Dan: hell yeah.
Please capitalize `Hell yeah.`

2022-10-10 14:54 UTC, adiati98 commented on episodes/4_2.srt
>  Todd: yeah.
Please capitalize the `Yeah.`

2022-10-10 15:35 UTC, ClJarvis commented on episodes/4_2.srt
> +welcome to season four, episode
√

2022-10-10 15:50 UTC, ClJarvis commented on episodes/4_2.srt
> +like that Todd:  I will use
Yes, I did that in a few places. I ran check program and it showed some of them with a warning. I fixed the ones it showed.

2022-10-10 15:53 UTC, danieltott commented
Thank you @ClJarvis @adiati98 for the work so far!

@ClJarvis I wanted to call out this comment: https://github.com/Virtual-Coffee/podcast-transcripts/pull/78#discussion_r991322100

Any time there's a speaker change, it'll require a new line/timestamp etc.

2022-10-10 15:57 UTC, ClJarvis commented on episodes/4_2.srt
> +to that. Yeah. Dan: honestly
I'm watching on the site. Is there way to get the more detailed time stamp?

Or do I just estimate and make sure one ends before the next one starts?

2022-10-10 16:46 UTC, ClJarvis commented on episodes/4_2.srt
> +uh, take any version. Bekah:
And that includes a new Number for the time stamp? and those that follow.  New speaker means up the timestamp item number up for all timestamps that follow?

282
00:15:34,100 --> 00:15:34,366
Dan: Honestly

2022-10-10 19:37 UTC, ClJarvis commented
I made the changes, fixed capitalization, gave new lines for new speakers, and reran the check.

2022-10-11 09:34 UTC, adiati98 commented
@ClJarvis Awesome! Thanks!
I will do the last edit from my side. Please give me a day or two (max. 3) for each episode because I'm doing something else too atm 😊

@danieltott I've created remote repo based on @ClJarvis's in my local for last editing.
I might need your help later on how to co-author and push the changes so I don't mess with Chris's PR for Hacktoberfest 😁
Thank you!

2022-10-11 20:41 UTC, danieltott commented
@ClJarvis We really prefer each PR to contain one issue's worth of work. If you could revert the changes to `3_9` and add them in a new branch and create a new PR, that would be awesome 👍🏼

2022-10-11 20:45 UTC, ClJarvis commented
All ready working on it. Didn't realized that the new episode was pushed to the first PR.

2022-10-11 21:02 UTC, ClJarvis commented
@danieltott Both branches should be fixed now.

2022-10-12 18:40 UTC, merged